name: API CI 
#ON PUSH
# on: [push]
on:
  push:
    paths:
      - "./api/**"
      - "./.github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Set up Node.js
        run: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        shell: bash
        run: npm install
      - name: Run unit tests
        shell: bash
        run: npm run test
